# Generated by Django 5.1.6 on 2025-03-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmodel',
            name='trailer',
        ),
    ]
