# Generated by Django 5.1.6 on 2025-03-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_moviesmodel_movies_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie_app.moviesmodel'),
        ),
    ]
