# Generated by Django 5.1.6 on 2025-03-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_remove_directormodel_movies_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directormodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie_app.directormodel'),
        ),
    ]
