# Generated by Django 5.1.6 on 2025-03-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_directormodel_name_alter_moviesmodel_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='movies',
            new_name='movie',
        ),
    ]
